# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class UsageAgreement(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, text=None, version=None, start_date=None, end_date=None):  # noqa: E501
        """UsageAgreement - a model defined in OpenAPI

        :param text: The text of this UsageAgreement.  # noqa: E501
        :type text: str
        :param version: The version of this UsageAgreement.  # noqa: E501
        :type version: float
        :param start_date: The start_date of this UsageAgreement.  # noqa: E501
        :type start_date: date
        :param end_date: The end_date of this UsageAgreement.  # noqa: E501
        :type end_date: date
        """
        self.openapi_types = {
            'text': str,
            'version': float,
            'start_date': date,
            'end_date': date
        }

        self.attribute_map = {
            'text': 'text',
            'version': 'version',
            'start_date': 'start_date',
            'end_date': 'end_date'
        }

        self._text = text
        self._version = version
        self._start_date = start_date
        self._end_date = end_date

    @classmethod
    def from_dict(cls, dikt) -> 'UsageAgreement':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The UsageAgreement of this UsageAgreement.  # noqa: E501
        :rtype: UsageAgreement
        """
        return util.deserialize_model(dikt, cls)

    @property
    def text(self):
        """Gets the text of this UsageAgreement.

        The contents of the usage agreement.  # noqa: E501

        :return: The text of this UsageAgreement.
        :rtype: str
        """
        return self._text

    @text.setter
    def text(self, text):
        """Sets the text of this UsageAgreement.

        The contents of the usage agreement.  # noqa: E501

        :param text: The text of this UsageAgreement.
        :type text: str
        """

        self._text = text

    @property
    def version(self):
        """Gets the version of this UsageAgreement.

        The verison of the agreement  # noqa: E501

        :return: The version of this UsageAgreement.
        :rtype: float
        """
        return self._version

    @version.setter
    def version(self, version):
        """Sets the version of this UsageAgreement.

        The verison of the agreement  # noqa: E501

        :param version: The version of this UsageAgreement.
        :type version: float
        """

        self._version = version

    @property
    def start_date(self):
        """Gets the start_date of this UsageAgreement.

        The date the agreement began  # noqa: E501

        :return: The start_date of this UsageAgreement.
        :rtype: date
        """
        return self._start_date

    @start_date.setter
    def start_date(self, start_date):
        """Sets the start_date of this UsageAgreement.

        The date the agreement began  # noqa: E501

        :param start_date: The start_date of this UsageAgreement.
        :type start_date: date
        """

        self._start_date = start_date

    @property
    def end_date(self):
        """Gets the end_date of this UsageAgreement.

        The date the agreement expires  # noqa: E501

        :return: The end_date of this UsageAgreement.
        :rtype: date
        """
        return self._end_date

    @end_date.setter
    def end_date(self, end_date):
        """Sets the end_date of this UsageAgreement.

        The date the agreement expires  # noqa: E501

        :param end_date: The end_date of this UsageAgreement.
        :type end_date: date
        """

        self._end_date = end_date
